### ISSUE TITLE
serilog property with space in start and end

### ISSUE THREAD

**Issue by teotws** [fvoncina/Serilog.Sinks.Loki.gRCP#5]

**Comment by teotws** [comment]
something like {ApplicationName=" XXX_Local "}, is it a feture or a bug?

**Comment by teotws** [comment]
Serilog-Sinks-Loki  log like  {ApplicationName="XXX_Local"}

**Comment by fvoncina** [comment]
Loki gRPC does not allows spaces and other characters in the key of the label, the function here is doing the cleanup: https://github.com/fvoncina/Serilog.Sinks.Loki.gRCP/blob/edeff0f12872f86ff9deca575da3c6ab981d1686/src/Serilog.Sinks.Loki.gRPC/Extensions.cs#L73
